### ISSUE TITLE
Deploy service broker into PAS

### ISSUE THREAD

**Issue by jasonmimick** [jasonmimick/atlas-osb#1]
Try to deploy and instance of the Atlas Service Broker to the pcf-test PCF cluster.

Document steps and create issues for any problems.

Prep for more official documentation and guidance for customers to deploy into VMware Tanzu environments.

**Comment by jasonmimick** [comment]
> ```How to deploy AOSB
Cf push

cf service-brokers
cf create-service-broker --help

cf create-service-broker mongodb-atlas nzjkbcly@5b2d0283df9db13a59085100 'a787fe68-2fd4-42fa-a3d5-72d322c77514' <http://mongodb-atlas.apps.test.pcf-test.com> 

cf service-access
cf enable-service-access
cf enable-service-access mongodb-atlas-aws

Check PCF App 

cf create-service mongodb-atlas-aws M10 Andrey_AWS_Test -c '{"cluster":  {"providerSettings":  {"regionName": "EU_CENTRAL_1"} } }'```
<sub>[View in Slack](https://mongodb.slack.com/archives/DBH9VKBJS/p1586955401000300)</sub>

**Comment by jeegarghodasara** [comment]
I am not sure what's going on in the step "create-service-broker" :

cf create-service-broker mongodb-atlas nzjkbcly@5b2d0283df9db13a59085100 'a787fe68-2fd4-42fa-a3d5-72d322c77514' <http://mongodb-atlas.apps.test.pcf-test.com> 

Does Customer need to download the "broker" first?

**Comment by jasonmimick** [comment]
Hi @jeegarghodasara -
The `cf push` command is meant to be run from a clone of this repo. This is what would deploy an app running the broker to some known url.

The `cf create-service-broker` commands then registers an instance of the atlas-osb hosted at [http://mongodb-atlas.apps.test.pct-test.com](http://mongodb-atlas.apps.test.pct-test.com). This means the DNS/etc is all setup. You can theoretically host this broker anywhere at all, or use the `cf push` to run locally.

The "big numbers" are ONE Atlas programmatic apikey, in a special format - and these are the credentials used by the broker to create and delete Atlas clusters.

```bash
cf create-service <service_name> <public_apikey>@<atlas_project_id> <private_apikey> <atlas-osb-url>
```

**Comment by jasonmimick** [comment]
complete - see docs
