### ISSUE TITLE
multi-key testing: catalog shows that all service plans are free (by default) 

### ISSUE THREAD

**Issue by leo-ri** [jasonmimick/atlas-osb#13]
Marketplace catalog has a default value in the "free or paid" column
_**cf marketplace -s mongodb-atlas-aws**_
service plan   description            free or paid
M10-valley     Instance size "M10"    free
M20-valley     Instance size "M20"    free
M40-valley     Instance size "M40"    free
M50-valley     Instance size "M50"    free
M60-valley     Instance size "M60"    free
M80-valley     Instance size "M80"    free
M200-valley    Instance size "M200"   free
M30-valley     Instance size "M30"    free
M90-valley     Instance size "M90"    free
Results: all plans are free
Expectation: plans have real "free/paid" status

We don't set "free" parameter at [service plan ](https://github.com/jasonmimick/atlas-osb/blob/a7e8d8fb6cce06c94fb8215466ebadc4ab24d839/pkg/broker/catalog.go#L187)

Also, we need to set provider too, VCAP right now
_"provider": null_ 
Expectation: "provider": "aws" (sample)

**Comment by jasonmimick** [comment]
All plans should default to free = false.

**Comment by jasonmimick** [comment]
Moving this bug to post Alpha sprint.
We need to evaluate solution based on adding more cf packaging, manifest.yml/etc.
