### ISSUE TITLE
Sprint 2 - Dev Preview Release Milestone Requirements

### ISSUE THREAD

**Issue by jasonmimick** [jasonmimick/atlas-osb#16]
This milestone marks the first "deliverable" in the sense that we will cut a release (tarball) and deliver this to be tested in customer environments. Not for production use.

For reference, we are targeting our core scenario called [Basic Plan](https://github.com/jasonmimick/atlas-osb/blob/ymlplans/docs/basic-plan.yml). This is a plan which models 1 project, 1 cluster, 1 user, and 1 ip-whitelist.

These requirements are also documented in [Issue 22](https://github.com/jasonmimick/atlas-osb/issues/22). Please review the specific customer notes in [22](https://github.com/jasonmimick/atlas-osb/issues/22) and each associated issue.

This release should be tested and validated for and initial "user acceptance test" of the [Basic Plan](https://github.com/jasonmimick/atlas-osb/blob/ymlplans/docs/basic-plan.yml) in the [Custom Plan Templates](https://github.com/jasonmimick/atlas-osb/blob/ymlplans/docs/custom-plans.md) project.

The specific items for this milestone are - link new tickets for these.

* Multiple Atlas apikey support. [Issue 24](https://github.com/jasonmimick/atlas-osb/issues/24)

* Provisioning, deprovisioning for the [Basic Plan](https://github.com/jasonmimick/atlas-osb/blob/ymlplans/docs/basic-plan.yml)
[Issue 17](https://github.com/jasonmimick/atlas-osb/issues/17)

* Bind and unbind for the [Basic Plan](https://github.com/jasonmimick/atlas-osb/blob/ymlplans/docs/basic-plan.yml)
[Issue 18](https://github.com/jasonmimick/atlas-osb/issues/18)

    1. Allow specification of the name of the database to connect to in the connection string. :question: Does this need to be the string "default" or the concept of the "default database for MongoDB" (which is usually the "test" database).
   2. Ensure connection string satisfies the requirements for [Binding/Unbinding](https://github.com/jasonmimick/atlas-osb/blob/ymlplans/docs/custom-plans.md#bind--unbind) 
[Issue 19](https://github.com/jasonmimick/atlas-osb/issues/19)

* Update for the [Basic Plan](https://github.com/jasonmimick/atlas-osb/blob/ymlplans/docs/basic-plan.yml)
[Issue 20](https://github.com/jasonmimick/atlas-osb/issues/20)

**Comment by jasonmimick** [comment]
- add issue to retire old broker mode support
- issue to track setup and test of basic plan in pcf 
- basic plan provision, deprovision
- basic plan bind/unbind
- bind spec update
- a ticket track close on "plan instance state mgmt" (what we will support s3? and exact req. - need PCF solution validated)

**Comment by gabimr** [comment]
From Sani:

### **Requirements for Sprint 2:** 
 
### 1. Support for default database (“default” not “test”)

See an example of binding data below:
{
"database": "default",
"password": "xxxxxxxxx",
"servers": [
  "10.225.12.33:27017",
  "10.225.12.41:27017",
  "10.225.12.34:27017"
],
"ssl": true,
"uri": "mongodb+srv://username:password@bb263ce0-6825-418c-b54e.cfh3t.azure.mongodb.net/defautl?retryWrites=true"
"username": "pcf_9717b61228c709afd0590a115bedc
}
 

 
### 2. Support  create-service-key with custom roles
Example: cf create-service-key my-atlas my-migration-user -c '{"roles":["clusterMonitor","readAnyDatabase"]}'
 
### 3. Support for multiple plans per broker
 
### 4. Documentation (and examples) on how to install and configure (using Env variables)  the Broker.
