### ISSUE TITLE
Creating service with the same name shows wrong status

### ISSUE THREAD

**Issue by leo-ri** [jasonmimick/atlas-osb#33]
before: `aws-atlas-test-instance-master-man-4d541d1` service is exist
if we call cf create-service with the same name 

output:
"Creating service instance aws-atlas-test-instance-master-man-4d541d1 in org atlas-test-master-man / space 4d541d1 as admin...
OK

Service aws-atlas-test-instance-master-man-4d541d1 already exists"

Result: status OK
Expectation: status FAILED

**Comment by vasilevp** [comment]
Not our problem - this is how CF works.
