### ISSUE TITLE
[Feature Request] ability to pause a cluster through the service broker

### ISSUE THREAD

**Issue by tanjoht** [jasonmimick/atlas-osb#44]
Need the ability to pause cluster. (extend the cluster class to have "paused" parameter type boolean? (reference: https://www.terraform.io/docs/providers/mongodbatlas/r/cluster.html)

**Comment by jasonmimick** [comment]
Hi John,

We should already support this - did you try it? If you did and got an error or non-expected result please attach to this issue.
FYI - here is an example below and we also documented this for the 1st release here: https://github.com/jasonmimick/atlas-osb/blob/master/docs/getting-started-cf-atlas-osb.md#pausing-a-cluster

```bash
cf update-service wed-demo-1 -c '{ "paused":true }'                
Updating service instance wed-demo-1 as admin...
OK
```

And if you get and setup [mongocli](https://github.com/mongodb/mongocli) (our new admin cli, then you can verify things right from the command line with things like this (also using [jq](https://stedolan.github.io/jq/) to parse the output).
```bash
➜  atlas-osb-MASTER-DEMO git:(master) ✗ mongocli atlas clusters list --projectId 5f0f0e0859cd8a08718294bf | jq '.[] | { "n" : .name, "s" : .paused}'
{
  "n": "wed-demo-1",
  "s": true
}
```

**Comment by tanjoht** [comment]
successfully tested pause and unpause.

cf update-service atlas-replica-m10-test1 -c '{ "paused":false }'
