### ISSUE TITLE
Feature Request: Allow customization of various fields

### ISSUE THREAD

**Issue by tanjoht** [jasonmimick/atlas-osb#49]
Would like to be able to customize the following fields:

service name: from "mongodb-atlas-template" to a customizable value

service template display name: from "MongoDB Atlas - Template Services" to a customizable value

service template description: from "MonogoDB Atlas Plan Template Deployments" to a customizable value

**Comment by tanjoht** [comment]
service name -> can use BROKER_OSB_SERVICE_NAME env

**Comment by jasonmimick** [comment]
We will be exposing setting for these parameters through additional broker environment variables.
Each of these are optional, and will have default content.
Here are the setting for the `domain.Service` returned for each plan:

domain.Service:
| Field | Env variable | Default |
| ----- | ------------- | --------- |
| `ID` | NONE | `"<id>-template-service"` |
| `Name` | `BROKER_OSB_SERVICE_NAME` | `"atlas"` |
| `Description` | `BROKER_OSB_SERVICE_DESC` | `"MonogoDB Atlas Plan Template Deployments"` |
| `Metadata.DisplayName` | `BROKER_OSB_SERVICE_DISPLAY_NAME` | `"MongoDB Atlas - %s"` with `"Template Services"` |
| `Metadata.ImageUrl` | `BROKER_OSB_IMAGE_URL` | `"https://webassets.mongodb.com/_com_assets/cms/vectors-anchor-circle-mydmar539a.svg"` |
| `DocumentationUrl` | `BROKER_OSB_DOCS_URL` | `"https://support.mongodb.com/welcome"` |
| `ProviderDisplayName` | `BROKER_OSB_PROVIDER_DISPLAY_NAME` | `"MongoDB"` |
| `LongDescription` | | `"Complete MongoDB Atlas deployments managed through resource templates. See https://github.com/jasonmimick/atlas-osb"` |
	
This will be available when the storage branch merges into master and is stable.

**Comment by tanjoht** [comment]
Hi Jason,

This would be perfect. I believe "BROKER_OSB_SERVICE_NAME" is already incorporated into the existing code - I've tested it and it works as expected.

**Comment by jasonmimick** [comment]
Merged and updated docs here:

https://github.com/jasonmimick/atlas-osb/blob/master/docs/atlas-osb-readme.md#osb-service-metadata-configuration-reference
